fix(Connectors & Webhook): add new types to Connector and make changes in WebhookEventPayload id.
pluggyai/pluggy-net pull request #16
Opened 2023-03-31 14:59 UTC by sebipap

2023-03-31 15:14 UTC, NicolasMontone requested changes

2023-03-31 15:14 UTC, NicolasMontone commented on Pluggy.Client/Program.cs
>                      ConnectorType.INVESTMENT
missing "," to separate type.

2023-04-04 15:48 UTC, Gabrielpanga approved these changes

2023-04-26 13:16 UTC, NicolasMontone requested changes

2023-04-26 13:16 UTC, NicolasMontone commented on Pluggy.SDK/Model/Webhook.cs
> +        [Obsolete("Use EventId instead", true)]
```suggestion
        [Obsolete("Use EventId instead", false)]
```
Setting it to `true` will cause compilation errors.

2023-05-02 12:48 UTC, merged